// Auto-generated from client/src/data/players.js by scripts/sync-roster.js
const PLAYER_ROSTER = {
  "josh allen": { id: "p1", team: "BUF", pos: "QB" },
  "drake maye": { id: "p2", team: "NE", pos: "QB" },
  "matthew stafford": { id: "p3", team: "LA", pos: "QB" },
  "patrick mahomes": { id: "p4", team: "KC", pos: "QB" },
  "trevor lawrence": { id: "p5", team: "JAX", pos: "QB" },
  "brock purdy": { id: "p6", team: "SF", pos: "QB" },
  "jalen hurts": { id: "p7", team: "PHI", pos: "QB" },
  "caleb williams": { id: "p8", team: "CHI", pos: "QB" },
  "dak prescott": { id: "p9", team: "DAL", pos: "QB" },
  "justin herbert": { id: "p10", team: "LAC", pos: "QB" },
  "bo nix": { id: "p11", team: "DEN", pos: "QB" },
  "jared goff": { id: "p12", team: "DET", pos: "QB" },
  "daniel jones": { id: "p13", team: "IND", pos: "QB" },
  "jaxson dart": { id: "p14", team: "NYG", pos: "QB" },
  "joe burrow": { id: "p15", team: "CIN", pos: "QB" },
  "lamar jackson": { id: "p16", team: "BAL", pos: "QB" },
  "jayden daniels": { id: "p17", team: "WAS", pos: "QB" },
  "jacoby brissett": { id: "p18", team: "ARI", pos: "QB" },
  "baker mayfield": { id: "p19", team: "TB", pos: "QB" },
  "justin fields": { id: "p20", team: "NYJ", pos: "QB" },
  "jordan love": { id: "p21", team: "GB", pos: "QB" },
  "kyler murray": { id: "p22", team: "ARI", pos: "QB" },
  "c.j. stroud": { id: "p23", team: "HOU", pos: "QB" },
  "jameis winston": { id: "p24", team: "NYG", pos: "QB" },
  "tyler shough": { id: "p25", team: "NO", pos: "QB" },
  "aaron rodgers": { id: "p26", team: "PIT", pos: "QB" },
  "carson wentz": { id: "p27", team: "MIN", pos: "QB" },
  "sam darnold": { id: "p28", team: "SEA", pos: "QB" },
  "bryce young": { id: "p29", team: "CAR", pos: "QB" },
  "michael penix jr.": { id: "p30", team: "ATL", pos: "QB" },
  "malik willis": { id: "p31", team: "GB", pos: "QB" },
  "marcus mariota": { id: "p32", team: "WAS", pos: "QB" },
  "christian mccaffrey": { id: "p33", team: "SF", pos: "RB" },
  "bijan robinson": { id: "p34", team: "ATL", pos: "RB" },
  "jahmyr gibbs": { id: "p35", team: "DET", pos: "RB" },
  "jonathan taylor": { id: "p36", team: "IND", pos: "RB" },
  "de'von achane": { id: "p37", team: "MIA", pos: "RB" },
  "james cook": { id: "p38", team: "BUF", pos: "RB" },
  "chase brown": { id: "p39", team: "CIN", pos: "RB" },
  "derrick henry": { id: "p40", team: "BAL", pos: "RB" },
  "cam skattebo": { id: "p41", team: "NYG", pos: "RB" },
  "josh jacobs": { id: "p42", team: "GB", pos: "RB" },
  "kyren williams": { id: "p43", team: "LA", pos: "RB" },
  "javonte williams": { id: "p44", team: "DAL", pos: "RB" },
  "omarion hampton": { id: "p45", team: "LAC", pos: "RB" },
  "travis etienne": { id: "p46", team: "JAX", pos: "RB" },
  "saquon barkley": { id: "p47", team: "PHI", pos: "RB" },
  "ashton jeanty": { id: "p48", team: "LV", pos: "RB" },
  "d'andre swift": { id: "p49", team: "CHI", pos: "RB" },
  "bucky irving": { id: "p50", team: "TB", pos: "RB" },
  "jaylen warren": { id: "p51", team: "PIT", pos: "RB" },
  "kenneth gainwell": { id: "p52", team: "PIT", pos: "RB" },
  "breece hall": { id: "p53", team: "NYJ", pos: "RB" },
  "rhamondre stevenson": { id: "p54", team: "NE", pos: "RB" },
  "rico dowdle": { id: "p55", team: "CAR", pos: "RB" },
  "rj harvey": { id: "p56", team: "DEN", pos: "RB" },
  "treveyon henderson": { id: "p57", team: "NE", pos: "RB" },
  "quinshon judkins": { id: "p58", team: "CLE", pos: "RB" },
  "j.k. dobbins": { id: "p59", team: "DEN", pos: "RB" },
  "kenneth walker iii": { id: "p60", team: "SEA", pos: "RB" },
  "zach charbonnet": { id: "p61", team: "SEA", pos: "RB" },
  "james conner": { id: "p62", team: "ARI", pos: "RB" },
  "tony pollard": { id: "p63", team: "TEN", pos: "RB" },
  "tyrone tracy jr.": { id: "p64", team: "NYG", pos: "RB" },
  "aaron jones": { id: "p65", team: "MIN", pos: "RB" },
  "david montgomery": { id: "p66", team: "DET", pos: "RB" },
  "audric estimé": { id: "p67", team: "NO", pos: "RB" },
  "alvin kamara": { id: "p68", team: "NO", pos: "RB" },
  "kimani vidal": { id: "p69", team: "LAC", pos: "RB" },
  "woody marks": { id: "p70", team: "HOU", pos: "RB" },
  "trey benson": { id: "p71", team: "ARI", pos: "RB" },
  "kareem hunt": { id: "p72", team: "KC", pos: "RB" },
  "tyjae spears": { id: "p73", team: "TEN", pos: "RB" },
  "kyle monangai": { id: "p74", team: "CHI", pos: "RB" },
  "chuba hubbard": { id: "p75", team: "CAR", pos: "RB" },
  "rachaad white": { id: "p76", team: "TB", pos: "RB" },
  "jacory croskey-merritt": { id: "p77", team: "WAS", pos: "RB" },
  "jordan mason": { id: "p78", team: "MIN", pos: "RB" },
  "bam knight": { id: "p79", team: "ARI", pos: "RB" },
  "chris rodriguez jr.": { id: "p80", team: "WAS", pos: "RB" },
  "michael carter": { id: "p81", team: "ARI", pos: "RB" },
  "jawhar jordan": { id: "p82", team: "HOU", pos: "RB" },
  "tyler allgeier": { id: "p83", team: "ATL", pos: "RB" },
  "blake corum": { id: "p84", team: "LA", pos: "RB" },
  "miles sanders": { id: "p85", team: "DAL", pos: "RB" },
  "isiah pacheco": { id: "p86", team: "KC", pos: "RB" },
  "devin neal": { id: "p87", team: "NO", pos: "RB" },
  "justice hill": { id: "p88", team: "BAL", pos: "RB" },
  "devin singletary": { id: "p89", team: "NYG", pos: "RB" },
  "nick chubb": { id: "p90", team: "HOU", pos: "RB" },
  "ty johnson": { id: "p91", team: "BUF", pos: "RB" },
  "bhayshul tuten": { id: "p92", team: "JAX", pos: "RB" },
  "dylan sampson": { id: "p93", team: "CLE", pos: "RB" },
  "emanuel wilson": { id: "p94", team: "GB", pos: "RB" },
  "sean tucker": { id: "p95", team: "TB", pos: "RB" },
  "jaylen wright": { id: "p96", team: "MIA", pos: "RB" },
  "samaje perine": { id: "p97", team: "CIN", pos: "RB" },
  "raheim sanders": { id: "p98", team: "CLE", pos: "RB" },
  "emari demercado": { id: "p99", team: "ARI", pos: "RB" },
  "kendre miller": { id: "p100", team: "NO", pos: "RB" },
  "antonio gibson": { id: "p101", team: "NE", pos: "RB" },
  "jeremy mcnichols": { id: "p102", team: "WAS", pos: "RB" },
  "isaiah davis": { id: "p103", team: "NYJ", pos: "RB" },
  "jaret patterson": { id: "p104", team: "LAC", pos: "RB" },
  "keaton mitchell": { id: "p105", team: "BAL", pos: "RB" },
  "malik davis": { id: "p106", team: "DAL", pos: "RB" },
  "jaydon blue": { id: "p107", team: "DAL", pos: "RB" },
  "najee harris": { id: "p108", team: "LAC", pos: "RB" },
  "jaleel mclaughlin": { id: "p109", team: "DEN", pos: "RB" },
  "braelon allen": { id: "p110", team: "NYJ", pos: "RB" },
  "ray davis": { id: "p111", team: "BUF", pos: "RB" },
  "brian robinson": { id: "p112", team: "SF", pos: "RB" },
  "puka nacua": { id: "p113", team: "LA", pos: "WR" },
  "jaxon smith-njigba": { id: "p114", team: "SEA", pos: "WR" },
  "ja'marr chase": { id: "p115", team: "CIN", pos: "WR" },
  "amon-ra st. brown": { id: "p116", team: "DET", pos: "WR" },
  "rashee rice": { id: "p117", team: "KC", pos: "WR" },
  "george pickens": { id: "p118", team: "DAL", pos: "WR" },
  "drake london": { id: "p119", team: "ATL", pos: "WR" },
  "chris olave": { id: "p120", team: "NO", pos: "WR" },
  "davante adams": { id: "p121", team: "LA", pos: "WR" },
  "ceedee lamb": { id: "p122", team: "DAL", pos: "WR" },
  "nico collins": { id: "p123", team: "HOU", pos: "WR" },
  "a.j. brown": { id: "p124", team: "PHI", pos: "WR" },
  "zay flowers": { id: "p125", team: "BAL", pos: "WR" },
  "malik nabers": { id: "p126", team: "NYG", pos: "WR" },
  "garrett wilson": { id: "p127", team: "NYJ", pos: "WR" },
  "tee higgins": { id: "p128", team: "CIN", pos: "WR" },
  "wan'dale robinson": { id: "p129", team: "NYG", pos: "WR" },
  "tyreek hill": { id: "p130", team: "MIA", pos: "WR" },
  "christian watson": { id: "p131", team: "GB", pos: "WR" },
  "quentin johnston": { id: "p132", team: "LAC", pos: "WR" },
  "michael wilson": { id: "p133", team: "ARI", pos: "WR" },
  "courtland sutton": { id: "p134", team: "DEN", pos: "WR" },
  "jameson williams": { id: "p135", team: "DET", pos: "WR" },
  "tetairoa mcmillan": { id: "p136", team: "CAR", pos: "WR" },
  "dk metcalf": { id: "p137", team: "PIT", pos: "WR" },
  "stefon diggs": { id: "p138", team: "NE", pos: "WR" },
  "alec pierce": { id: "p139", team: "IND", pos: "WR" },
  "rome odunze": { id: "p140", team: "CHI", pos: "WR" },
  "jaylen waddle": { id: "p141", team: "MIA", pos: "WR" },
  "michael pittman": { id: "p142", team: "IND", pos: "WR" },
  "justin jefferson": { id: "p143", team: "MIN", pos: "WR" },
  "devonta smith": { id: "p144", team: "PHI", pos: "WR" },
  "deebo samuel sr.": { id: "p145", team: "WAS", pos: "WR" },
  "jauan jennings": { id: "p146", team: "SF", pos: "WR" },
  "parker washington": { id: "p147", team: "JAX", pos: "WR" },
  "emeka egbuka": { id: "p148", team: "TB", pos: "WR" },
  "terry mclaurin": { id: "p149", team: "WAS", pos: "WR" },
  "ladd mcconkey": { id: "p150", team: "LAC", pos: "WR" },
  "jakobi meyers": { id: "p151", team: "JAX", pos: "WR" },
  "keenan allen": { id: "p152", team: "LAC", pos: "WR" },
  "marvin harrison jr.": { id: "p153", team: "ARI", pos: "WR" },
  "mike evans": { id: "p154", team: "TB", pos: "WR" },
  "khalil shakir": { id: "p155", team: "BUF", pos: "WR" },
  "troy franklin": { id: "p156", team: "DEN", pos: "WR" },
  "romeo doubs": { id: "p157", team: "GB", pos: "WR" },
  "dj moore": { id: "p158", team: "CHI", pos: "WR" },
  "brian thomas jr.": { id: "p159", team: "JAX", pos: "WR" },
  "ricky pearsall": { id: "p160", team: "SF", pos: "WR" },
  "jordan addison": { id: "p161", team: "MIN", pos: "WR" },
  "jayden reed": { id: "p162", team: "GB", pos: "WR" },
  "tre tucker": { id: "p163", team: "LV", pos: "WR" },
  "chris godwin jr.": { id: "p164", team: "TB", pos: "WR" },
  "travis hunter": { id: "p165", team: "JAX", pos: "WR" },
  "kayshon boutte": { id: "p166", team: "NE", pos: "WR" },
  "rashid shaheed": { id: "p167", team: "SEA", pos: "WR" },
  "josh downs": { id: "p168", team: "IND", pos: "WR" },
  "marquise brown": { id: "p169", team: "KC", pos: "WR" },
  "theo wease jr.": { id: "p170", team: "MIA", pos: "WR" },
  "keon coleman": { id: "p171", team: "BUF", pos: "WR" },
  "luther burden iii": { id: "p172", team: "CHI", pos: "WR" },
  "jalen coker": { id: "p173", team: "CAR", pos: "WR" },
  "mack hollins": { id: "p174", team: "NE", pos: "WR" },
  "tory horton": { id: "p175", team: "SEA", pos: "WR" },
  "xavier worthy": { id: "p176", team: "KC", pos: "WR" },
  "ryan flournoy": { id: "p177", team: "DAL", pos: "WR" },
  "jayden higgins": { id: "p178", team: "HOU", pos: "WR" },
  "jalen mcmillan": { id: "p179", team: "TB", pos: "WR" },
  "chimere dike": { id: "p180", team: "TEN", pos: "WR" },
  "devaughn vele": { id: "p181", team: "NO", pos: "WR" },
  "cooper kupp": { id: "p182", team: "SEA", pos: "WR" },
  "elic ayomanor": { id: "p183", team: "TEN", pos: "WR" },
  "darius slayton": { id: "p184", team: "NYG", pos: "WR" },
  "jerry jeudy": { id: "p185", team: "CLE", pos: "WR" },
  "malik washington": { id: "p186", team: "MIA", pos: "WR" },
  "calvin ridley": { id: "p187", team: "TEN", pos: "WR" },
  "tyquan thornton": { id: "p188", team: "KC", pos: "WR" },
  "kendrick bourne": { id: "p189", team: "SF", pos: "WR" },
  "kevin austin jr.": { id: "p190", team: "NO", pos: "WR" },
  "sterling shepard": { id: "p191", team: "TB", pos: "WR" },
  "greg dortch": { id: "p192", team: "ARI", pos: "WR" },
  "trey mcbride": { id: "p193", team: "ARI", pos: "TE" },
  "george kittle": { id: "p194", team: "SF", pos: "TE" },
  "tucker kraft": { id: "p195", team: "GB", pos: "TE" },
  "brock bowers": { id: "p196", team: "LV", pos: "TE" },
  "kyle pitts": { id: "p197", team: "ATL", pos: "TE" },
  "dallas goedert": { id: "p198", team: "PHI", pos: "TE" },
  "sam laporta": { id: "p199", team: "DET", pos: "TE" },
  "harold fannin jr.": { id: "p200", team: "CLE", pos: "TE" },
  "travis kelce": { id: "p201", team: "KC", pos: "TE" },
  "jake ferguson": { id: "p202", team: "DAL", pos: "TE" },
  "tyler warren": { id: "p203", team: "IND", pos: "TE" },
  "juwan johnson": { id: "p204", team: "NO", pos: "TE" },
  "hunter henry": { id: "p205", team: "NE", pos: "TE" },
  "dalton schultz": { id: "p206", team: "HOU", pos: "TE" },
  "dalton kincaid": { id: "p207", team: "BUF", pos: "TE" },
  "colston loveland": { id: "p208", team: "CHI", pos: "TE" },
  "darren waller": { id: "p209", team: "MIA", pos: "TE" },
  "brenton strange": { id: "p210", team: "JAX", pos: "TE" },
  "zach ertz": { id: "p211", team: "WAS", pos: "TE" },
  "colby parkinson": { id: "p212", team: "LA", pos: "TE" },
  "jake tonges": { id: "p213", team: "SF", pos: "TE" },
  "oronde gadsden ii": { id: "p214", team: "LAC", pos: "TE" },
  "aj barner": { id: "p215", team: "SEA", pos: "TE" },
  "theo johnson": { id: "p216", team: "NYG", pos: "TE" },
  "cade otton": { id: "p217", team: "TB", pos: "TE" },
  "david njoku": { id: "p218", team: "CLE", pos: "TE" },
  "mark andrews": { id: "p219", team: "BAL", pos: "TE" },
  "pat freiermuth": { id: "p220", team: "PIT", pos: "TE" },
  "t.j. hockenson": { id: "p221", team: "MIN", pos: "TE" },
  "chig okonkwo": { id: "p222", team: "TEN", pos: "TE" },
  "tyler higbee": { id: "p223", team: "LA", pos: "TE" },
  "greg dulcich": { id: "p224", team: "MIA", pos: "TE" },
  "mason taylor": { id: "p225", team: "NYJ", pos: "TE" },
  "dawson knox": { id: "p226", team: "BUF", pos: "TE" },
  "evan engram": { id: "p227", team: "DEN", pos: "TE" },
  "mike gesicki": { id: "p228", team: "CIN", pos: "TE" },
  "ka'imi fairbairn": { id: "p229", team: "HOU", pos: "K" },
  "jason myers": { id: "p230", team: "SEA", pos: "K" },
  "spencer shrader": { id: "p231", team: "IND", pos: "K" },
  "brandon aubrey": { id: "p232", team: "DAL", pos: "K" },
  "zane gonzalez": { id: "p233", team: "ATL", pos: "K" },
  "ben sauls": { id: "p234", team: "NYG", pos: "K" },
  "eddy pineiro": { id: "p235", team: "SF", pos: "K" },
  "cameron dicker": { id: "p236", team: "LAC", pos: "K" },
  "charlie smyth": { id: "p237", team: "NO", pos: "K" },
  "cam little": { id: "p238", team: "JAX", pos: "K" },
  "will reichard": { id: "p239", team: "MIN", pos: "K" },
  "chase mclaughlin": { id: "p240", team: "TB", pos: "K" },
  "harrison mevis": { id: "p241", team: "LA", pos: "K" },
  "jake moody": { id: "p242", team: "WAS", pos: "K" },
  "chris boswell": { id: "p243", team: "PIT", pos: "K" },
  "jake bates": { id: "p244", team: "DET", pos: "K" },
  "cairo santos": { id: "p245", team: "CHI", pos: "K" },
  "harrison butker": { id: "p246", team: "KC", pos: "K" },
  "andy borregales": { id: "p247", team: "NE", pos: "K" },
  "tyler loop": { id: "p248", team: "BAL", pos: "K" },
  "joey slye": { id: "p249", team: "TEN", pos: "K" },
  "brandon mcmanus": { id: "p250", team: "GB", pos: "K" },
  "blake grupe": { id: "p251", team: "IND", pos: "K" },
  "evan mcpherson": { id: "p252", team: "CIN", pos: "K" },
  "nick folk": { id: "p253", team: "NYJ", pos: "K" },
  "wil lutz": { id: "p254", team: "DEN", pos: "K" },
  "graham gano": { id: "p255", team: "NYG", pos: "K" },
  "riley patterson": { id: "p256", team: "MIA", pos: "K" },
  "matt gay": { id: "p257", team: "SF", pos: "K" },
  "chad ryland": { id: "p258", team: "ARI", pos: "K" },
  "lucas havrisik": { id: "p259", team: "GB", pos: "K" },
  "matt prater": { id: "p260", team: "BUF", pos: "K" },
  "buffalo bills d/st": { id: "p261", team: "BUF", pos: "DEF" },
  "philadelphia eagles d/st": { id: "p262", team: "PHI", pos: "DEF" },
  "baltimore ravens d/st": { id: "p263", team: "BAL", pos: "DEF" },
  "denver broncos d/st": { id: "p264", team: "DEN", pos: "DEF" },
  "minnesota vikings d/st": { id: "p265", team: "MIN", pos: "DEF" },
  "pittsburgh steelers d/st": { id: "p266", team: "PIT", pos: "DEF" },
  "san francisco 49ers d/st": { id: "p267", team: "SF", pos: "DEF" },
  "detroit lions d/st": { id: "p268", team: "DET", pos: "DEF" },
  "kansas city chiefs d/st": { id: "p269", team: "KC", pos: "DEF" },
  "houston texans d/st": { id: "p270", team: "HOU", pos: "DEF" },
  "los angeles chargers d/st": { id: "p271", team: "LAC", pos: "DEF" },
  "green bay packers d/st": { id: "p272", team: "GB", pos: "DEF" },
  "chicago bears d/st": { id: "p273", team: "CHI", pos: "DEF" },
  "dallas cowboys d/st": { id: "p274", team: "DAL", pos: "DEF" },
  "cleveland browns d/st": { id: "p275", team: "CLE", pos: "DEF" },
  "new york jets d/st": { id: "p276", team: "NYJ", pos: "DEF" },
  "tampa bay buccaneers d/st": { id: "p277", team: "TB", pos: "DEF" },
  "miami dolphins d/st": { id: "p278", team: "MIA", pos: "DEF" },
  "new orleans saints d/st": { id: "p279", team: "NO", pos: "DEF" },
  "seattle seahawks d/st": { id: "p280", team: "SEA", pos: "DEF" },
  "cincinnati bengals d/st": { id: "p281", team: "CIN", pos: "DEF" },
  "washington commanders d/st": { id: "p282", team: "WAS", pos: "DEF" },
  "indianapolis colts d/st": { id: "p283", team: "IND", pos: "DEF" },
  "los angeles rams d/st": { id: "p284", team: "LA", pos: "DEF" },
  "atlanta falcons d/st": { id: "p285", team: "ATL", pos: "DEF" },
  "arizona cardinals d/st": { id: "p286", team: "ARI", pos: "DEF" },
  "new york giants d/st": { id: "p287", team: "NYG", pos: "DEF" },
  "jacksonville jaguars d/st": { id: "p288", team: "JAX", pos: "DEF" },
  "tennessee titans d/st": { id: "p289", team: "TEN", pos: "DEF" },
  "new england patriots d/st": { id: "p290", team: "NE", pos: "DEF" },
  "las vegas raiders d/st": { id: "p291", team: "LV", pos: "DEF" },
  "carolina panthers d/st": { id: "p292", team: "CAR", pos: "DEF" },
  "deandre carter": { id: "p293", team: "CLE", pos: "WR" },
  "trent taylor": { id: "p294", team: "SF", pos: "WR" },
  "mike williams": { id: "p295", team: "LAC", pos: "WR" },
  "deshaun watson": { id: "p296", team: "CLE", pos: "QB" },
  "noah brown": { id: "p297", team: "WAS", pos: "WR" },
  "austin ekeler": { id: "p298", team: "WAS", pos: "RB" },
  "zay jones": { id: "p299", team: "ARI", pos: "WR" },
  "joe mixon": { id: "p300", team: "HOU", pos: "RB" },
  "josh reynolds": { id: "p301", team: "NYJ", pos: "WR" },
  "irv smith": { id: "p302", team: "HOU", pos: "TE" },
  "alexander mattison": { id: "p303", team: "MIA", pos: "RB" },
  "foster moreau": { id: "p304", team: "NO", pos: "TE" },
  "gardner minshew": { id: "p305", team: "KC", pos: "QB" },
  "donald parham": { id: "p306", team: "PIT", pos: "TE" },
  "salvon ahmed": { id: "p307", team: "IND", pos: "RB" },
  "gabe davis": { id: "p308", team: "BUF", pos: "WR" },
  "brandon aiyuk": { id: "p309", team: "SF", pos: "WR" },
  "van jefferson": { id: "p310", team: "TEN", pos: "WR" },
  "brevin jordan": { id: "p311", team: "HOU", pos: "TE" },
  "brock wright": { id: "p312", team: "DET", pos: "TE" },
  "rondale moore": { id: "p313", team: "MIN", pos: "WR" },
  "josh palmer": { id: "p314", team: "BUF", pos: "WR" },
  "jerome ford": { id: "p315", team: "CLE", pos: "RB" },
  "darnell washington": { id: "p316", team: "PIT", pos: "TE" },
  "tank dell": { id: "p317", team: "HOU", pos: "WR" },
  "roschon johnson": { id: "p318", team: "CHI", pos: "RB" },
  "trey palmer": { id: "p319", team: "NO", pos: "WR" },
  "will levis": { id: "p320", team: "TEN", pos: "QB" },
  "anthony richardson": { id: "p321", team: "IND", pos: "QB" },
  "luke mccaffrey": { id: "p322", team: "WAS", pos: "WR" },
  "ja'tavion sanders": { id: "p323", team: "CAR", pos: "TE" },
  "jaylin lane": { id: "p324", team: "WAS", pos: "WR" },
};

module.exports = { PLAYER_ROSTER };
